# Generated by Django 5.2.8 on 2026-01-11 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedfile',
            old_name='uploaded_at',
            new_name='created_at',
        ),
    ]
