# Generated by Django 5.2.8 on 2026-01-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_uploaded_at_sharedfile_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharedfile',
            name='code',
            field=models.CharField(db_index=True, max_length=5),
        ),
    ]
